name: Verify changes

on: [pull_request]

jobs:
  verify:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Install xmllint
        run: sudo apt-get install -y shellcheck

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
        name: Install dependencies

      - run: yarn verify:bail
        name: Verify changes

      - name: Publish coverage to codecov.io
        uses: codecov/codecov-action@v1
        if: success() && matrix.node-version == '12.x'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          yml: ./codecov.yml
